# Generated by Django 6.0.3 on 2026-03-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0002_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
