# Generated by Django 6.0.3 on 2026-03-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0003_alter_article_title_alter_article_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["title", "category"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-year", "-month"]},
        ),
    ]
