# Generated by Django 5.2.4 on 2026-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0007_alter_article_options_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
