# Generated by Django 5.2.4 on 2026-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobe_wave', '0008_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
