# Generated by Django 6.0.3 on 2026-03-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id_category", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("words", models.TextField()),
                ("rgb", models.CharField(max_length=200)),
                ("hsl", models.CharField(max_length=200)),
                ("hexadecimal", models.CharField(max_length=7)),
                ("red", models.IntegerField()),
                ("green", models.IntegerField()),
                ("blue", models.IntegerField()),
                ("hue", models.IntegerField()),
                ("sat", models.IntegerField()),
                ("bri", models.IntegerField()),
            ],
            options={
                "db_table": "image",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id_articles", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kobe_wave.category",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        db_column="id_image",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kobe_wave.image",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
            },
        ),
    ]
