# Generated by Django 6.0.3 on 2026-03-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
