# Generated by Django 6.0.3 on 2026-03-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0004_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(fields=("url",), name="unique_article_url"),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                fields=("filename", "year", "month"),
                name="unique_image_filename_year_month",
            ),
        ),
    ]
