# Generated by Django 6.0.3 on 2026-03-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kobe_wave", "0005_article_unique_article_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="filename",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="check_month_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1900)), name="check_year_valide"
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("red__gte", 0), ("red__lte", 255)),
                name="check_red_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("green__gte", 0), ("green__lte", 255)),
                name="check_green_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("blue__gte", 0), ("blue__lte", 255)),
                name="check_blue_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("hue__gte", 0), ("hue__lte", 360)),
                name="check_hue_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("sat__gte", 0), ("sat__lte", 100)),
                name="check_sat_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("bri__gte", 0), ("bri__lte", 100)),
                name="check_bri_valide",
            ),
        ),
    ]
